version = 1

test_patterns = ["src/test/*"]

exclude_patterns = [
    "docs/*",
    "gradle/*",
    "src/main/frontend/*",
    "src/main/resources/*"
]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "15"
